global:
  scrape_interval: 5s # Scrape frequently for demo purposes (usually 15s-1m in prod)

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'twitte-service'
    static_configs:
      - targets: ['twitte-service:2112']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:2112']

  - job_name: 'users-service'
    static_configs:
      - targets: ['users-service:2112']

  - job_name: 'timeline-service'
    static_configs:
      - targets: ['timeline-service:2112']
